### PR TITLE
SDL2 port

### PR DESCRIPTION
**Pull request by ujmm**
Tested and working on Linux and Windows, Code::Blocks project files and *nix Makefile have been updated but vcpp and xcode projects have not been touched so they won't work as they'll try to link against SDL1.

### CODE REVIEW

**Comment by RonaldReagan** [comment]
Is text in menus missing as well? Is anything displayed in the bigger console mode (F11)? I can't reproduce this behaviour on any of my systems, but I have a feeling it's a texture issue.

The text was working in the menus, some images were getting loaded while others weren't. I'll try to fix it. Just didn't know if you had similar issues.

**Comment by jmmaunus** [comment]
FWIW I looked at the texture files for all the missing GUI elements - there isn't much to look at, but it looks like the missing elements all have textures with transparency. Can you try loading flag modes and see if flag icons are visible? Or possibly just temporarily replace the textures with something that has no transparency just to see if they're visible at all.

**Comment by ac-stef** [comment]
our SDL2 port is currently pending in experimental - and it is based on this PR, thx

**Comment by drian0** [comment]
Thank you very much, your PR is part of the upcoming release.

**Pull request closed without merging**
