### PR TITLE
Allow build with systems libenet

### PR DESCRIPTION
**Pull request by susnux**
Make it possible to build with system libenet, so packaging is easier.
This is already done by Arch Linux or openSUSE.

### CODE REVIEW

**Comment by ac-stef** [comment]
Unless those distributions plan to synchronize future updates of their enet packages with the release dates of AC, this is a horrible idea.
The enet library in use is part of the AC game protocol - _which is the reason for us to have enet sources included in our package in the first place_.
If Arch or oS actually mess up AC by using a different enet library, **I'm going to give their maintainers' home phone numbers to everyone who comes to us with a support case because of this!**.
Don't build packages, if you don't know what you're doing!

**Comment by susnux** [comment]
Of cause, but normally if  the protocol changes also the version of enet changes so the .so number will change.
You can have multiple different versions of libraries on your system so there should be no problem if there are different versions.
(The packagers should of cause keep track on changes and require the matching version).

**Comment by ac-stef** [comment]
Why on earth should we open that can of worms just to eliminate 50k of static library? (Also, 1.2.0.2 already fails on some platforms, because it requires an old version of libcurl.)

Just think of it as a code part of AC that looks very much like a commonly known network libarary.

Btw: recent development versions are no longer compatible to stock enet anyway :)

**Comment by susnux** [comment]
Ok.
I tested this patch with the current git head (feb 27) and with enet7 (1.3.13).
No problems after some hours of playing the game :-)

**Comment by ac-stef** [comment]
a) "it's working now" is irrelevant, as long as you can't guarantee the system enet library to stay compatible
b) last year, our enet code received a security fix that will not be fixed in the official enet sources
c) our enet sources already provide API extensions that are in use by commits that have not yet been merged with the main repository (check my branch "pit")

There is absolutely nothing to gain for us by using the system lib for enet.
Instead, we would open up a potential support hell.

**Comment by susnux** [comment]
Ok

**Pull request closed without merging**
