### PR TITLE
fix linkage issue for *BSD system

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by ac-stef** [comment]
What's the error message if you omit libintl?
BSD has a librt - what's the issue?
Why commit three unchanges files?

**Comment by devnexen** [comment]
on BSD libintl is needed for get text matters. You re right for second statement for FreeBSD though, OpenBSD does not have.

**Comment by ac-stef** [comment]
What's the error message if you omit libintl?

**Comment by devnexen** [comment]
my bad, does not seem needed finally.

**Comment by ac-stef** [comment]
Does this work for you or do you actually require the mode changes on those two enet files?

**Comment by devnexen** [comment]
It was needed for the master branch but for this next one it seems ok, I have made the change under OpenBSD though since once there is a release will try to push a package of it.

**Comment by ac-stef** [comment]
The master branch doesn't compile if source/enet/Makefile.in and source/enet/aclocal.m4 are not changed from 100755 to 100644? What's the error message?

Does baa44b5 work for you?

**Comment by devnexen** [comment]
Yes @ac-stef it does work

**Comment by ac-stef** [comment]
Thx.

**Pull request closed without merging**
