### PR TITLE
This commit attempts to fix issue #408

### PR DESCRIPTION
**Pull request by Noah11012**

### CODE REVIEW

**Comment by baarreth** [comment]
Thank you for your pull request.
Using a slightly modified one (below), it seems to solve the unicode issue in the comments (at least for the case I was testing). We just need to think a little more about whether there will be other cases that will bring unexpected behavior.

```
  bool incomment = false;
  loopk(cfglen) {
      if(( cfgraw[k] > 0x7f || (cfgraw[k] < 0x20 && !isspace(cfgraw[k])) ) && !incomment) err = "illegal chars in cfg file";
      if(cfgraw[k] == '/' && cfgraw[k + 1] == '/') // Note(EveryRelease): Don't report illegal characters in comments.
          incomment = true;
      else if(cfgraw[k] == '\n')
          incomment = false;
  }

```

**Comment by Noah11012** [comment]
I don't know much about config files in AssaultCube but what about strings? Do we and is it a good idea to allow "illegal chars" in them?

**Comment by Noah11012** [comment]
Should I close this pull request?

**Comment by baarreth** [comment]
At this time, I think it is a good idea to close this pull request for now. We should think more if we should or shouldn't allow unicode chars in the cfg. Maybe it is better to simply inform the client that he should remove them.

Anyway, thank you again for your time. We really appreciate your help.

**Pull request closed without merging**
