### PR TITLE
Implement infix modification operators

### PR DESCRIPTION
**Pull request by acgybe**
Hello!

I've added infix modification operators: `+=`, `-=`, `*=`, etc. They work just as `=` infix shorthand for `alias`. Looking through scripts in `config/`, infix `=` is used more often than `alias` (and, IMHO, looks better), so perhaps infix modification operators will come in handy as well.

### CODE REVIEW

**Comment by acgybe** [comment]
Of course, I could add infix versions of arithmetic and logical operators as well, but they still don't look natural (except to Lisp programmers) when expressions are more complex, e.g. `(+ $a (+ $b $c))` vs. `($a + ($b + $c))`, because of the extra parentheses.

**Comment by ac-stef** [comment]
IMHO, a few infix operators in a predominantly prefix language do not "look better".

I'd rather remove the infix "=".

**Comment by acgybe** [comment]
> a few infix operators in a predominantly prefix language do not "look better".

I agree with that, but a language with console-style call syntax (space separated arguments) does not have to use prefix notation for operators. Although having to put space around operators is sometimes awkward, with some precedence parsing we could have something like `foo = $bar * 2 + $baz` being equivalent to `alias foo (+ (* $bar 2) $baz)`. Then the language turns into a strange PHP with square brackets instead of curly braces and without need to put commas between function arguments, or parentheses around them. Again, except for people who like Lisps, I think that would be an improvement, as far as arithmetic and logical operations go.

But I could be wrong, or it could be not worth it. Either way, I've learned how CubeScript is implemented (mostly) =D. Should I close this or is there someone else who could weigh in?

**Comment by ac-stef** [comment]
I'll leave it as an exercise for the reader, why the relevant difference between `foo = $bar * 2 + $baz` and `alias foo (+ (* $bar 2) $baz)` is not the infix notation.

If you insist, I'll remove the "=".

**Comment by acgybe** [comment]
I don't see it. Although there should be parentheses around right hand side of assignment. But they could be inserted automatically as well (when there are several arguments after '=').

I don't insist on removing '=', it would be an inconvenient breaking change.

**Comment by ac-stef** [comment]
Parentheses are the main building block of every non-trivial cubescript command. To replace or "automatically insert" them would require a completely different parser - basically a different language.

**Pull request closed without merging**
