### PR TITLE
Cleanedit Mode

### PR DESCRIPTION
**Pull request by Felix-The-Ghost**
Commands and documentation for /cleanedit and /togglecleanedit.

Hides ALL editing related graphics to edit with unobstructed view of
cube/entity changes.

cleanedit is the user VAR and can be fetched in CS. togglecleanedit is
the bindable command and the intended way to toggle the value of
$cleanedit.

### CODE REVIEW

**Comment by drian0** [comment]
Thank you very much for this pull request. We added it to the upcoming release.

**Comment by Felix-The-Ghost** [comment]
I completely forgot about this lol

This is one of the functions from my mapping client edit

A few years ago I privately gave the source to Lucas and I also publicly released a patch and I'm told that some of it made it in but I'm not specifically aware.

This year I updated the thread with example images and minor updates to the documentation

https://forum.cubers.net/thread-7663.html

Sorry I don't have a setup atm to officially do pull requests and I've been out of the loop for a while

**Comment by Felix-The-Ghost** [comment]
If previous comment was TL;DR

I heard some of my previous work had already been in, so I guess it should be verified that merging this pull request isn't redundant from already being in, in some form

**Comment by drian0** [comment]
Thanks for the update :) I will consult with grenadier.

**Comment by Felix-The-Ghost** [comment]
Forum user "Brutal System" was the one that filled me in

Per: https://forum.cubers.net/thread-9083-post-174532.html#pid174532

But I can't specifically verify atm

**Comment by BrutalSystem** [comment]
20210415_20 02 02_dev_dusk_coop
I think "cleanedit" should not superimpose this options enabled.
and should not hide clips & new clips.

**Comment by Felix-The-Ghost** [comment]
That specifically is the purpose of it though.
It doesn't change those settings just takes precedence.

So when you're flying around you see the map exactly as a player would

It was designed to be toggled on and off with a default bind when desired

It is maybe something to explore if those dialogs can read the value of $cleanedit when toggling and put text in the console if you think there's a possibility of people being confused. Another option could be during cleanedit show the command to exit cleanedit or have some dialog for it.

It doesn't confuse me but I also designed it and used it extensively so I'm glad we are indeed considering it from the view of a new player. I just wouldn't want to compromise the actual functionality Itself for the sake of clarity but I'm not used to some other methods used to make clear what's happening during clean edit.

**Pull request closed without merging**
